CREATE TABLE "LOTTERY_EVENT_WINNER" (
	"LEW_SEQ"	INTEGER NOT NULL UNIQUE,
	"LEW_LEM_SEQ"	INTEGER NOT NULL,
	"LEW_LEP_SEQ"	INTEGER NOT NULL,
	"LEW_USER_ID"	INTEGER NOT NULL,
	"LEW_USER_NAME"	TEXT NOT NULL,
	"LEW_BATCH"	INTEGER NOT NULL,
	"LEW_HAS_CLAIM"	INTEGER NOT NULL DEFAULT 0,
	"LEW_WINNER_TIME"	TEXT NOT NULL DEFAULT (DATETIME('Now', 'LocalTime')),
	CONSTRAINT "LEW_PK" PRIMARY KEY("LEW_SEQ" AUTOINCREMENT),
	CONSTRAINT "LEW_FK_M" FOREIGN KEY("LEW_LEM_SEQ") REFERENCES "LOTTERY_EVENT_MASTER"("LEM_SEQ"),
	CONSTRAINT "LEW_FK_P" FOREIGN KEY("LEW_LEP_SEQ") REFERENCES "LOTTERY_EVENT_PARTICIPANT"("LEP_SEQ")
);