CREATE TABLE "BOT_PARAM_DETAIL" (
	"BPD_SEQ"	INTEGER NOT NULL UNIQUE,
	"BPD_BPM_SEQ"	INTEGER NOT NULL,
	"BPD_BOT_ID"	TEXT NOT NULL,
	"BPD_MODULE_ID"	TEXT NOT NULL,
	"BPD_PARAM_TYPE"	TEXT NOT NULL,
	"BPD_GUILD_ID"	INTEGER NOT NULL DEFAULT -1,
	"BPD_PARAM_ID"	TEXT NOT NULL,
	"BPD_PARAM_VALUE"	TEXT NOT NULL,
	"BPD_PARAM_NAME"	TEXT,
	"BPD_PARAM_ATTR"	TEXT,
	"BPD_PARAM_DESC"	TEXT,
	CONSTRAINT "BPD_UK" UNIQUE("BPD_BOT_ID","BPD_MODULE_ID","BPD_PARAM_TYPE","BPD_GUILD_ID","BPD_PARAM_ID"),
	CONSTRAINT "BPD_PK" PRIMARY KEY("BPD_SEQ" AUTOINCREMENT),
	CONSTRAINT "BPD_FK" FOREIGN KEY("BPD_BPM_SEQ") REFERENCES "BOT_PARAM_MASTER"("BPM_SEQ")
);