CREATE TABLE "LOTTERY_EVENT_PARTICIPANT" (
	"LEP_SEQ"	INTEGER NOT NULL UNIQUE,
	"LEP_LEM_SEQ"	INTEGER NOT NULL,
	"LEP_USER_ID"	INTEGER NOT NULL,
	"LEP_USER_NAME"	TEXT NOT NULL,
	"LEP_JOIN_TIME"	TEXT NOT NULL DEFAULT (DATETIME('Now', 'LocalTime')),
	CONSTRAINT "LEP_UK" UNIQUE("LEP_LEM_SEQ","LEP_USER_ID"),
	CONSTRAINT "LEP_PK" PRIMARY KEY("LEP_SEQ" AUTOINCREMENT),
	CONSTRAINT "LEP_FK" FOREIGN KEY("LEP_LEM_SEQ") REFERENCES "LOTTERY_EVENT_MASTER"("LEM_SEQ")
);