CREATE TABLE "BOT_PARAM_MASTER" (
	"BPM_SEQ"	INTEGER NOT NULL UNIQUE,
	"BPM_BOT_ID"	TEXT NOT NULL,
	"BPM_MODULE_ID"	TEXT NOT NULL,
	"BPM_PARAM_TYPE"	TEXT NOT NULL,
	"BPM_PARAM_DESC"	TEXT,
	CONSTRAINT "BPM_UK" UNIQUE("BPM_BOT_ID","BPM_MODULE_ID","BPM_PARAM_TYPE"),
	CONSTRAINT "BPM_PK" PRIMARY KEY("BPM_SEQ" AUTOINCREMENT)
);